name: Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: yarn install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
